server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
#    active: aggregation
     active: dev
  data:
    redis:
      host: 192.168.188.123
      port: 6379
      password: 826929
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848