server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.188.123
      port: 6379
      password: 826929
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis:
  #  引入配置文件
  #  config-location: classpath:/mybatis-config.xml
  #  设置资源路径
  mapper-locations: classpath:/Mapper/*/*.xml

shortLink:
  amap:
    key: 460c0075ca51d0ba13afb4e6deb14d32
  domain:
    default: qx.ink:8001

goto-domain:
  white-list:
    enable: true
    names: '拿个offer,知乎,掘金,博客园'
    details:
      - nageoffer.com
      - zhihu.com
      - juejin.cn
      - cnblogs.com

